development: &defaults
  # These are the settings for repository :default
  adapter:  sqlite3
  database: schema/sample_development.sqlite3
 
  # Add more repositories
  # repositories:
  #   repo1:
  #     adapter:  sqlite3
  #     database: sample_1_development.sqlite3
  #   repo2:
  #     ...
 
test:
  <<:       *defaults
  database: schema/sample_test.sqlite3
 
  # repositories:
  #   repo1:
  #     database: sample_1_test.sqlite3
 
production:
  <<:       *defaults
  database: schema/production.sqlite3
 
  # repositories:
  #   repo1:
  #     database: sample_production.sqlite3
 
rake:
  <<: *defaults
